name: Automatic notebook cleaning
on:
  push:
    paths:
    - '**.ipynb'
jobs:
  clean-ipynb-output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
      - name: Installing nbconvert
        run: |
          pip install nbconvert
      - name: Running nbbconvert
        run: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace notebook.ipynb
