name: Automatic Code Cleaning & Formatter
on:
  push:
    paths:
    - '**.py'
    - '**.ipynb'
jobs:
  clean-and-format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
      - name: Installing nbconvert
        run: |
          pip install nbconvert
      - name: Running nbbconvert and clear all notebook outputs
        run: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace notebook.ipynb
      - name: Autoformatting with autoyapf  # performing auto-formatting with autoyapf
        id: autoyapf
        uses: mritunjaysharma394/autoyapf@v2
        with:
          args: --style pep8 --recursive --in-place .
      - name: Checking for modified files  # checks differences
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Pushing formatted files changes
        if: steps.git-check.outputs.modified == 'true'
        run: | # identity...
          git config --global user.name 'autoyapf-formatter-action'
          git config --global user.email 'mansitos97@gmail.com' 
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "🍃 Automated Code Cleaning 🍃"
          git push
